# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0border.proto\x12\x06server\",\n\x08OrderReq\x12\x0f\n\x07good_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\".\n\nOrderReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\tb\x06proto3'
)




_ORDERREQ = _descriptor.Descriptor(
  name='OrderReq',
  full_name='server.OrderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='good_id', full_name='server.OrderReq.good_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='server.OrderReq.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=67,
)


_ORDERREPLY = _descriptor.Descriptor(
  name='OrderReply',
  full_name='server.OrderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='server.OrderReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='server.OrderReply.order_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['OrderReq'] = _ORDERREQ
DESCRIPTOR.message_types_by_name['OrderReply'] = _ORDERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderReq = _reflection.GeneratedProtocolMessageType('OrderReq', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQ,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:server.OrderReq)
  })
_sym_db.RegisterMessage(OrderReq)

OrderReply = _reflection.GeneratedProtocolMessageType('OrderReply', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREPLY,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:server.OrderReply)
  })
_sym_db.RegisterMessage(OrderReply)


# @@protoc_insertion_point(module_scope)
