# 安装jemalloc 先写好命令 最后再统一格式
cd ~; wget https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2;
tar -jxvf jemalloc-5.2.1.tar.bz2;
cd jemalloc-5.2.1;
./configure –prefix=/usr/local/jemalloc
make -j8 ; make install

#安装xx

