# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pay.proto',
  package='server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tpay.proto\x12\x06server\",\n\x06PayReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08pay_code\x18\x02 \x01(\t\"\x1a\n\x08PayReply\x12\x0e\n\x06status\x18\x01 \x01(\tb\x06proto3'
)




_PAYREQ = _descriptor.Descriptor(
  name='PayReq',
  full_name='server.PayReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='server.PayReq.order_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pay_code', full_name='server.PayReq.pay_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=65,
)


_PAYREPLY = _descriptor.Descriptor(
  name='PayReply',
  full_name='server.PayReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='server.PayReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['PayReq'] = _PAYREQ
DESCRIPTOR.message_types_by_name['PayReply'] = _PAYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PayReq = _reflection.GeneratedProtocolMessageType('PayReq', (_message.Message,), {
  'DESCRIPTOR' : _PAYREQ,
  '__module__' : 'pay_pb2'
  # @@protoc_insertion_point(class_scope:server.PayReq)
  })
_sym_db.RegisterMessage(PayReq)

PayReply = _reflection.GeneratedProtocolMessageType('PayReply', (_message.Message,), {
  'DESCRIPTOR' : _PAYREPLY,
  '__module__' : 'pay_pb2'
  # @@protoc_insertion_point(class_scope:server.PayReply)
  })
_sym_db.RegisterMessage(PayReply)


# @@protoc_insertion_point(module_scope)
